version: '3.8'

services:
  flask1:
    build: ./app
    container_name: flask1
    networks:
      - lb_net

  flask2:
    build: ./app
    container_name: flask2
    networks:
      - lb_net

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    depends_on:
      - flask1
      - flask2
    networks:
      - lb_net

networks:
  lb_net:
