version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # RabbitMQ management UI

  celery_worker:
    build: .
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - rabbitmq

  django_app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
