version: "3.8"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    platform: linux/amd64  # Cố định nền tảng x86_64 cho WordPress
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    platform: linux/amd64  # Cố định nền tảng x86_64 cho MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
