version: '3'

services:
  # Dịch vụ MariaDB
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_password  # Đặt mật khẩu root cho MariaDB
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: nextcloud_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nextcloud_net

  # Dịch vụ Redis
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - nextcloud_net

  # Dịch vụ Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - 80:80  # Mở port 80 cho Nextcloud
    environment:
      MYSQL_PASSWORD: nextcloud_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud_user
      MYSQL_HOST: db
      REDIS_HOST: redis
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_net
    restart: always

volumes:
  db_data:
  nextcloud_data:

networks:
  nextcloud_net:
    driver: bridge
