version: "3.8"

services:
  redis:
    image: redis:latest  # Sử dụng Redis phiên bản mới nhất
    container_name: redis_container
    ports:
      - "6379:6379"  # Map cổng 6379 của container với cổng 6379 của máy host
    restart: always
