version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Gắn volume vào thư mục dữ liệu của MySQL

volumes:
  mysql-data:  # Khai báo volume
