version: '3.7'

services:
  # Traefik - Reverse Proxy
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"              # Kích hoạt giao diện API của Traefik
      - "--providers.docker=true"          # Kết nối Traefik với Docker provider
      - "--entrypoints.web.address=:80"    # Cấu hình entry point cho HTTP (port 80)
    ports:
      - "80:80"                            # Mở port 80 cho Traefik
      - "8080:8080"                        # Mở port 8080 cho giao diện quản lý Traefik (có thể tắt trong môi trường production)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"   # Cung cấp quyền truy cập vào Docker socket
    networks:
      - web

  # Dịch vụ Flask
  flask-app:
    build:
      context: ./flask  # Thư mục chứa Dockerfile cho Flask (tạo thư mục flask và Dockerfile tại đây)
    container_name: flask-app
    labels:
      - "traefik.enable=true"                 # Kích hoạt Traefik cho Flask app
      - "traefik.http.routers.flask.rule=Host(`flask.local`)"   # Định tuyến HTTP request tới Flask khi truy cập flask.local
      - "traefik.http.services.flask.loadbalancer.server.port=5000" # Chỉ định port mà Flask app đang chạy
    networks:
      - web

  # Dịch vụ WordPress
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=wordpress_db:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
    labels:
      - "traefik.enable=true"                             # Kích hoạt Traefik cho WordPress
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.local`)"  # Định tuyến HTTP request tới WordPress khi truy cập wordpress.local
      - "traefik.http.services.wordpress.loadbalancer.server.port=80" # Chỉ định port WordPress
    networks:
      - web
    depends_on:
      - wordpress_db

  # Dịch vụ MariaDB cho WordPress
  wordpress_db:
    image: mariadb:latest
    container_name: wordpress_db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    networks:
      - web

networks:
  web:
    driver: bridge
