version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - voting_net

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - voting_net

  vote:
    build: ./vote
    container_name: vote_app
    ports:
      - "5000:80"
    depends_on:
      - redis
    networks:
      - voting_net

  result:
    build: ./result
    container_name: result_app
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - voting_net

  worker:
    build: ./worker
    container_name: worker_app
    depends_on:
      - redis
      - db
    networks:
      - voting_net

volumes:
  db_data:

networks:
  voting_net:
