version: '3.8'

services:
  web:
    image: nginx
    container_name: web
    networks:
      - mynetwork

  api:
    image: httpd
    container_name: api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
